### PR TITLE
feat: Add Kusama and tickers

### PR DESCRIPTION
**Pull request by savudani8**

### CODE REVIEW

**Comment by theodorebugnet** [comment]
I'm not entirely convinced about extracting the strings into a separate file. An intended usecase is to allow people to easily define their own currencies in their personal codebase, without forking this repo, and so the currency definitions are mostly self-contained (other than of course depending on the base `MonetaryAmount` class).

While this change doesn't preclude that at all, it does make a distinction between "predefined" currencies which have their name stored in `CurrencyName`, and user-defined ones which would have to use their own strings. It also makes the existing definitions, e.g. `bitcoin.ts`, not directly usable as an example for a user to copy for their own currency.

A minor issue, to be sure, but in turn I'm not convinced of the benefit of this change. Ultimately, each currency definition basically exists to define the constants for that currency, such as the decimal places for the different units, the list of units in the first place, the decimals to which to round approximate human-friendly strings, etc. The currency name (and ticker) is just another constant. I'm not really sure whether there's any benefit in defining the name string in a separate file, away from all the other constant definitions.

**Comment by savudani8** [comment]
@theodorebugnet Usage without alteration of the `names.ts` file is exemplified in the tests. It would probably make sense for users of new currencies to declare their own Names enum, extending the default one, so as not to use magic strings throughout their code. I pushed a commit that removes these enums and we can think about it later.

**Comment by theodorebugnet** [comment]
Alright. My thinking though is that they're only magic strings as much as e.g. the decimal places are magic numbers. And all magic constants need to be declared somewhere, and in my mind it makes the most sense to treat a currency definition as the source of all the magic strings and magic numbers, because that's really what a currency is - it's basically defining the data, it's not got any logic.

If you disagree, I'll leave it up to you to decide whether to keep the enum or not. Everything else looks good so good for merging.

**Review by theodorebugnet — APPROVED** [review]

**Comment by savudani8** [comment]
Ah I see what you mean now! `Bitcoin.name` and `Bitcoin.ticker` can be used instead of additional enums

**Pull request merged**
